# Multi stage build optimization

name: CI
on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix Setup and Prerequisite Actions
        run: |
          nix develop --command bash -c '
            set -e
            uv sync
            uv run ruff check .
            uv run ruff format --check .
            uv run pytest -m unit
            uv run pytest -m integration
          '

  build:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Build the image
        run: |
            docker build -t registry.example.com/prod-app:${{ github.sha }} ./src

      - name: Healthcheck
        run: |
           docker run -d --name prod-app-container -p 8000:8000 registry.example.com/prod-app:${{ github.sha }}
           trap "docker logs prod-app-container; docker rm -f prod-app-container" EXIT
           for i in {1..30}; do
               if curl -fs http://localhost:8000/health; then
                   exit 0
               fi
               sleep 1
           done

           exit 1

      - name: Save Docker image
        run: |
          docker save \
            registry.example.com/prod-app:${{ github.sha }} \
            -o prod-app.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: prod-app
          path: prod-app.tar

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: prod-app

      - name: Load Docker image
        run: |
          docker load -i prod-app.tar

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.example.com
          username: ${{ secrets.REGISTRY_USERNAME }}    # Store the secrets in github
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push to registry
        run: |
          docker push registry.example.com/prod-app:${{ github.sha }}
